$(document).ready(function(){
    $('#leader_tab').click(function(){
        window.location.href="../html/leader.html"
    });
    $('#role_tab').click(function(){
        window.location.href="../html/role_setting.html"
    });
    $('#vote').click(function(){
        window.location.href="../html/vote2.html"
    });
});