$(document).ready(function(){
    $('#leader_tab').click(function(){
        window.location.href="../html/leader.html"
    });
    $('#role_tab').click(function(){
        window.location.href="../html/role_setting.html"
    });
    $('#restart_hover').click(function(){
        window.location.href="../html/role_setting.html"
    });
});
