$(document).ready(function(){
    $('#leader_tab').click(function(){
        window.location.href="leader.html"
    });
    $('#role_tab').click(function(){
        window.location.href="role_setting/role_setting.html"
    });
    $('#vote').click(function(){
        window.location.href="vote2.html"
    });
});